backend:
  name: git-gateway
  branch: main

media_folder: "src/uploads"
public_folder: "https://minimal-decap-cms-tests.netlify.app/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json" # Convert to JSON for better use of the elements
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string

      - label: Description
        name: description
        widget: text

      - label: Tags
        name: tags
        widget: list
        allow_add: true
        required: false


      - label: Options
        name: options
        widget: object
        collapsed: true
        fields:
          - label: Featured
            name: featured
            widget: boolean
            default: false
                  
          - label: Publish Date
            name: date
            widget: datetime
            default: "{{now}}"

          - label: Order
            name: order
            widget: number
            value_type: int


      - label: Cover Image
        name: image
        widget: image
        required: false

      - label: Body
        name: body
        widget: markdown